// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAoXKko1tQHtxdwcmrhQ_pCmcCr1VOjv6E',
    appId: '1:750686189500:web:814d77a53a298025eaddb9',
    messagingSenderId: '750686189500',
    projectId: 'chatapp-fb78e',
    authDomain: 'chatapp-fb78e.firebaseapp.com',
    storageBucket: 'chatapp-fb78e.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDcatldax23HGkYxnTU2qvJqUvhzXcGY0Q',
    appId: '1:750686189500:android:502e399612ac0924eaddb9',
    messagingSenderId: '750686189500',
    projectId: 'chatapp-fb78e',
    storageBucket: 'chatapp-fb78e.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAIvq7ZqNLbFe16Gt4NaVZ-ilrlXoajIpw',
    appId: '1:750686189500:ios:b0d44fc793687fb3eaddb9',
    messagingSenderId: '750686189500',
    projectId: 'chatapp-fb78e',
    storageBucket: 'chatapp-fb78e.firebasestorage.app',
    iosBundleId: 'com.example.chatapp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAIvq7ZqNLbFe16Gt4NaVZ-ilrlXoajIpw',
    appId: '1:750686189500:ios:b0d44fc793687fb3eaddb9',
    messagingSenderId: '750686189500',
    projectId: 'chatapp-fb78e',
    storageBucket: 'chatapp-fb78e.firebasestorage.app',
    iosBundleId: 'com.example.chatapp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAoXKko1tQHtxdwcmrhQ_pCmcCr1VOjv6E',
    appId: '1:750686189500:web:64f5a3927e08a62eeaddb9',
    messagingSenderId: '750686189500',
    projectId: 'chatapp-fb78e',
    authDomain: 'chatapp-fb78e.firebaseapp.com',
    storageBucket: 'chatapp-fb78e.firebasestorage.app',
  );
}
